# Generated by Django 4.1.5 on 2023-01-23 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FoodGroups',
            new_name='FoodGroup',
        ),
    ]
