# Generated by Django 4.1.5 on 2023-01-29 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_unitconversion_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unitconversion',
            name='name',
        ),
    ]
