# Generated by Django 4.1.5 on 2023-01-29 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_remove_unitconversion_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='shorthand',
            field=models.CharField(default='p', max_length=4),
            preserve_default=False,
        ),
    ]
